### PR TITLE
fix: Use unique user secrets id

### PR DESCRIPTION
**Pull request by davidw-foxtrax**
The initial id was accidentally duplicated with the SourceService.

### CODE REVIEW

**Comment by davidw-foxtrax** [comment]
@ChetanaRK 

I didn't properly regenerate the user secrets GUID between Source and Device, so right now they are the same (which means they use the same UserSecrets file, which they shouldn't.)

This will fix that, but when it is merged into master it will break your local configuration.

If you could, please make sure that your user config is copied somewhere safe (or just remember that you'll need to pull it while on a branch with the older id).

I'll wait until you approve this PR to do a merge so as not to break anything unexpectedly.

**Comment by ChetanaRK** [comment]
@davidw-foxtrax, 
I need clarification that once you regenerate the user config file, and if I have backup file stored, I will just have to replace it in local?
Is my understanding is correct David?

**Comment by davidw-foxtrax** [comment]
@ChetanaRK Yes.

The update will cause it to look for the file with the new id.  So, once this is merged, that will be an empty file.  You'll need to add your local config to that new file, just like this was a new checkout.

The important thing is to make sure you know what needs to be added (either by copy/paste or just be retyping the credentials),

**Comment by ChetanaRK** [comment]
@davidw-foxtrax, that should be fine, as I have kept the backup file. You can regenerate the file.

**Pull request merged**
